//Autenticacion
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";
export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";
export const ACTIVATION_FAIL = "ACTIVATION_FAIL";
export const SET_AUTH_LOADING = "SET_AUTH_LOADING";
export const REMOVE_AUTH_LOADING = "REMOVE_AUTH_LOADING";
export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";
export const REFRESH_SUCCESS = "REFRESH_SUCCESS";
export const REFRESH_FAIL = "REFRESH_FAIL";
export const LOGOUT = "LOGOUT";

export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const RESET_PASSWORD_CONFIRM_SUCCESS = "RESET_PASSWORD_CONFIRM_SUCCESS";
export const RESET_PASSWORD_CONFIRM_FAIL = "RESET_PASSWORD_CONFIRM_FAIL";

//Alertas
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

//Categorias
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAIL = "GET_CATEGORIES_FAIL";

//Servicios
export const GET_PUBLICATIONS_SUCCESS = "GET_PUBLICATIONS_SUCCESS";
export const GET_PUBLICATIONS_FAIL = "GET_PUBLICATIONS_FAIL";
export const GET_PUBLICATIONS_BY_ARRIVAL_SUCCESS =
  "GET_PUBLICATIONS_BY_ARRIVAL_SUCCESS";
export const GET_PUBLICATIONS_BY_ARRIVAL_FAIL =
  "GET_PUBLICATIONS_BY_ARRIVAL_FAIL";
export const GET_PUBLICATIONS_BY_SOLD_SUCCESS =
  "GET_PUBLICATIONS_BY_SOLD_SUCCESS";
export const GET_PUBLICATIONS_BY_SOLD_FAIL = "GET_PUBLICATIONS_BY_SOLD_FAIL";
export const GET_PUBLICATION_SUCCESS = "GET_PUBLICATION_SUCCESS";
export const GET_PUBLICATION_FAIL = "GET_PUBLICATION_FAIL";
export const SEARCH_PUBLICATIONS_SUCCESS = "SEARCH_PUBLICATIONS_SUCCESS";
export const SEARCH_PUBLICATIONS_FAIL = "SEARCH_PUBLICATIONS_FAIL";
export const RELATED_PUBLICATIONS_SUCCESS = "RELATED_PUBLICATIONS_SUCCESS";
export const RELATED_PUBLICATIONS_FAIL = "RELATED_PUBLICATIONS_FAIL";
export const FILTER_PUBLICATIONS_SUCCESS = "FILTER_PUBLICATIONS_SUCCESS";
export const FILTER_PUBLICATIONS_FAIL = "FILTER_PUBLICATIONS_FAIL";
export const CREATE_PUBLICATION_SUCCESS = "CREATE_PUBLICATION_SUCCESS";
export const CREATE_PUBLICATION_FAIL = "CREATE_PUBLICATION_FAIL";
export const UPDATE_PUBLICATION_SUCCESS = "UPDATE_PUBLICATION_SUCCESS";
export const UPDATE_PUBLICATION_FAIL = "UPDATE_PUBLICATION_FAIL";
export const DELETE_PUBLICATION_SUCCESS = "DELETE_PUBLICATION_SUCCESS";
export const DELETE_PUBLICATION_FAIL = "DELETE_PUBLICATION_FAIL";

//Perfil de usuario
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAIL = "GET_USER_PROFILE_FAIL";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAIL = "UPDATE_USER_PROFILE_FAIL";

//Usuarios
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";

//Notificaciones
export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS";
export const GET_NOTIFICATIONS_FAIL = "GET_NOTIFICATIONS_FAIL";
export const CREATE_NOTIFICATION_SUCCESS = "CREATE_NOTIFICATION_SUCCESS";
export const CREATE_NOTIFICATION_FAIL = "CREATE_NOTIFICATION_FAIL";
export const SEND_NOTIFICATION_SUCCESS = "SEND_NOTIFICATION_SUCCESS";
export const SEND_NOTIFICATION_FAIL = "SEND_NOTIFICATION_FAIL";
