//Autenticacion
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";
export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";
export const ACTIVATION_FAIL = "ACTIVATION_FAIL";
export const SET_AUTH_LOADING = "SET_AUTH_LOADING";
export const REMOVE_AUTH_LOADING = "REMOVE_AUTH_LOADING";
export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";
export const REFRESH_SUCCESS = "REFRESH_SUCCESS";
export const REFRESH_FAIL = "REFRESH_FAIL";
export const LOGOUT = "LOGOUT";

export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const RESET_PASSWORD_CONFIRM_SUCCESS = "RESET_PASSWORD_CONFIRM_SUCCESS";
export const RESET_PASSWORD_CONFIRM_FAIL = "RESET_PASSWORD_CONFIRM_FAIL";

//Alertas
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

//Categorias
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAIL = "GET_CATEGORIES_FAIL";

//Servicios
export const GET_SERVICES_SUCCESS = "GET_SERVICES_SUCCESS";
export const GET_SERVICES_FAIL = "GET_SERVICES_FAIL";
export const GET_SERVICES_BY_ARRIVAL_SUCCESS =
  "GET_SERVICES_BY_ARRIVAL_SUCCESS";
export const GET_SERVICES_BY_ARRIVAL_FAIL = "GET_SERVICES_BY_ARRIVAL_FAIL";
export const GET_SERVICES_BY_SOLD_SUCCESS = "GET_SERVICES_BY_SOLD_SUCCESS";
export const GET_SERVICES_BY_SOLD_FAIL = "GET_SERVICES_BY_SOLD_FAIL";
export const GET_SERVICE_SUCCESS = "GET_SERVICE_SUCCESS";
export const GET_SERVICE_FAIL = "GET_SERVICE_FAIL";
export const SEARCH_SERVICES_SUCCESS = "SEARCH_SERVICES_SUCCESS";
export const SEARCH_SERVICES_FAIL = "SEARCH_SERVICES_FAIL";
export const RELATED_SERVICES_SUCCESS = "RELATED_SERVICES_SUCCESS";
export const RELATED_SERVICES_FAIL = "RELATED_SERVICES_FAIL";
export const FILTER_SERVICES_SUCCESS = "FILTER_SERVICES_SUCCESS";
export const FILTER_SERVICES_FAIL = "FILTER_SERVICES_FAIL";
