# Generated by Django 4.2.2 on 2023-10-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/'),
        ),
    ]
