export const comunidadesAutonomas = [
  { id: 1, name: "Andalucía" },
  { id: 2, name: "Aragón" },
  { id: 3, name: "Asturias" },
  { id: 4, name: "Islas Baleares" },
  { id: 5, name: "Islas Canarias" },
  { id: 6, name: "Cantabria" },
  { id: 7, name: "Castilla-La Mancha" },
  { id: 8, name: "Castilla y León" },
  { id: 9, name: "Cataluña" },
  { id: 10, name: "Comunidad Valenciana" },
  { id: 11, name: "Extremadura" },
  { id: 12, name: "Galicia" },
  { id: 13, name: "Comunidad de Madrid" },
  { id: 14, name: "Región de Murcia" },
  { id: 15, name: "Comunidad Foral de Navarra" },
  { id: 16, name: "País Vasco (Euskadi)" },
  { id: 17, name: "La Rioja" },
  { id: 18, name: "Ceuta" },
  { id: 19, name: "Melilla" },
];
