# Use a lightweight base image
FROM nginx:alpine


RUN pwd

RUN ls -la /home/runner/work/Proyecto_TrendySwap/
# Copy the static website files to the Nginx document root
COPY /home/runner/work/Proyecto_TrendySwap/Frontend/* /usr/share/nginx/html